# Generated by Django 4.0.2 on 2022-02-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Silaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silaba_name', models.CharField(max_length=5)),
                ('palabras', models.ManyToManyField(to='syllableGame.Palabra')),
            ],
            options={
                'ordering': ['silaba_name'],
            },
        ),
    ]
