# Generated by Django 4.0.2 on 2022-02-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllableGame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img_address', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Syllabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabe_name', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['syllabe_name'],
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, null=True)),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllableGame.frase')),
                ('syllabe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllableGame.syllabe')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
