# Generated by Django 4.0.1 on 2022-07-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllableGame', '0002_frase_syllabe_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['frase', 'position']},
        ),
    ]
