# Generated by Django 4.0.6 on 2022-07-06 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllableGame', '0003_alter_element_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palabra',
            name='address',
        ),
        migrations.RemoveField(
            model_name='silaba',
            name='palabras',
        ),
        migrations.AddField(
            model_name='palabra',
            name='silaba',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='syllableGame.silaba'),
        ),
        migrations.AlterField(
            model_name='silaba',
            name='silaba_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
