# Generated by Django 4.0.6 on 2022-07-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableGame', '0004_remove_palabra_address_remove_silaba_palabras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabe',
            name='syllabe_name',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
