# Generated by Django 4.0.6 on 2022-07-06 22:45

from django.db import migrations, models
import django.db.models.deletion
import syllableGame.models


class Migration(migrations.Migration):

    dependencies = [
        ('syllableGame', '0006_alter_element_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='frase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllableGame.frase', validators=[syllableGame.models.restrict_amount]),
        ),
    ]
